// src/data.js — Thank You Jesus App — All Data & Translations

export const LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇬🇧', nativeName: 'English' },
  { code: 'es', name: 'Spanish', flag: '🇪🇸', nativeName: 'Español' },
  { code: 'pt', name: 'Portuguese', flag: '🇵🇹', nativeName: 'Português' },
  { code: 'it', name: 'Italian', flag: '🇮🇹', nativeName: 'Italiano' },
  { code: 'pl', name: 'Polish', flag: '🇵🇱', nativeName: 'Polski' },
  { code: 'de', name: 'German', flag: '🇩🇪', nativeName: 'Deutsch' },
  { code: 'fr', name: 'French', flag: '🇫🇷', nativeName: 'Français' },
  { code: 'ru', name: 'Russian', flag: '🇷🇺', nativeName: 'Русский' },
  { code: 'ro', name: 'Romanian', flag: '🇷🇴', nativeName: 'Română' },
  { code: 'sk', name: 'Slovak', flag: '🇸🇰', nativeName: 'Slovenčina' },
];

export const DENOMINATIONS = [
  { id: 'catholic',    icon: '✝️',  key: 'catholic' },
  { id: 'orthodox',   icon: '☦️',  key: 'orthodox' },
  { id: 'protestant', icon: '📖',  key: 'protestant' },
  { id: 'ecumenical', icon: '🕊️', key: 'ecumenical' },
  { id: 'seeker',     icon: '🔍',  key: 'seeker' },
];

export const QUICK_TOPICS = [
  { id: 'grief',       icon: '💔', bg: '#fde8e8', color: '#7B2020' },
  { id: 'fear',        icon: '😰', bg: '#e8f4e8', color: '#1A5C1A' },
  { id: 'decision',    icon: '🔀', bg: '#e8ecf8', color: '#1A2E6E' },
  { id: 'forgiveness', icon: '🤲', bg: '#f8f4e0', color: '#5C4A00' },
  { id: 'gratitude',   icon: '🙏', bg: '#f0e8f8', color: '#4A1A6E' },
  { id: 'love',        icon: '❤️', bg: '#fff0f0', color: '#8B0000' },
  { id: 'temptation',  icon: '⚠️', bg: '#fdf0e0', color: '#7B3B00' },
  { id: 'hope',        icon: '🌅', bg: '#e0f0fd', color: '#004A7B' },
];

export const BIBLE_TRANSLATIONS = {
  en: 'web', es: 'rvr1909', pt: 'arc', it: 'riveduta',
  pl: 'bg', de: 'luther1912', fr: 'lsg', ru: 'sinodal', ro: 'cornilescu', sk: 'web',
};

// 10 daily verses in English (other languages handled by AI)
export const DAILY_VERSES_EN = [
  { text: "For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life.", ref: "John 3:16" },
  { text: "I can do all things through Christ who strengthens me.", ref: "Philippians 4:13" },
  { text: "The Lord is my shepherd; I shall not want.", ref: "Psalm 23:1" },
  { text: "Come to me, all who labor and are heavy laden, and I will give you rest.", ref: "Matthew 11:28" },
  { text: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", ref: "Joshua 1:9" },
  { text: "Trust in the Lord with all your heart, and do not lean on your own understanding.", ref: "Proverbs 3:5" },
  { text: "And we know that for those who love God all things work together for good.", ref: "Romans 8:28" },
  { text: "I am the way, and the truth, and the life. No one comes to the Father except through me.", ref: "John 14:6" },
  { text: "For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope.", ref: "Jeremiah 29:11" },
  { text: "Peace I leave with you; my peace I give to you. Not as the world gives do I give to you. Let not your hearts be troubled.", ref: "John 14:27" },
];

export const BIBLE_TOPICS = [
  {
    id: 'love', icon: '❤️', color: '#e74c3c',
    verses: [
      { text: "Love is patient, love is kind. It does not envy, it does not boast, it is not proud.", ref: "1 Corinthians 13:4" },
      { text: "For God so loved the world, that he gave his only Son.", ref: "John 3:16" },
      { text: "We love because he first loved us.", ref: "1 John 4:19" },
      { text: "Greater love has no one than this: to lay down one's life for one's friends.", ref: "John 15:13" },
      { text: "And now these three remain: faith, hope and love. But the greatest of these is love.", ref: "1 Corinthians 13:13" },
    ],
  },
  {
    id: 'faith', icon: '✝️', color: '#8e44ad',
    verses: [
      { text: "Now faith is confidence in what we hope for and assurance about what we do not see.", ref: "Hebrews 11:1" },
      { text: "For we live by faith, not by sight.", ref: "2 Corinthians 5:7" },
      { text: "I can do all this through him who gives me strength.", ref: "Philippians 4:13" },
      { text: "Trust in the Lord with all your heart and lean not on your own understanding.", ref: "Proverbs 3:5" },
      { text: "Jesus said to him, 'I am the way, and the truth, and the life.'", ref: "John 14:6" },
    ],
  },
  {
    id: 'hope', icon: '🌅', color: '#f39c12',
    verses: [
      { text: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", ref: "Jeremiah 29:11" },
      { text: "May the God of hope fill you with all joy and peace as you trust in him.", ref: "Romans 15:13" },
      { text: "And we know that in all things God works for the good of those who love him.", ref: "Romans 8:28" },
      { text: "But those who hope in the Lord will renew their strength. They will soar on wings like eagles.", ref: "Isaiah 40:31" },
      { text: "Be joyful in hope, patient in affliction, faithful in prayer.", ref: "Romans 12:12" },
    ],
  },
  {
    id: 'peace', icon: '🕊️', color: '#27ae60',
    verses: [
      { text: "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled.", ref: "John 14:27" },
      { text: "And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.", ref: "Philippians 4:7" },
      { text: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.", ref: "Philippians 4:6" },
      { text: "The Lord gives strength to his people; the Lord blesses his people with peace.", ref: "Psalm 29:11" },
      { text: "Come to me, all you who are weary and burdened, and I will give you rest.", ref: "Matthew 11:28" },
    ],
  },
  {
    id: 'strength', icon: '💪', color: '#2980b9',
    verses: [
      { text: "I can do all this through him who gives me strength.", ref: "Philippians 4:13" },
      { text: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", ref: "Joshua 1:9" },
      { text: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", ref: "Psalm 28:7" },
      { text: "He gives strength to the weary and increases the power of the weak.", ref: "Isaiah 40:29" },
      { text: "For God has not given us a spirit of fear, but of power and of love and of a sound mind.", ref: "2 Timothy 1:7" },
    ],
  },
  {
    id: 'forgiveness', icon: '🤲', color: '#16a085',
    verses: [
      { text: "If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.", ref: "1 John 1:9" },
      { text: "Bear with each other and forgive one another if any of you has a grievance against someone. Forgive as the Lord forgave you.", ref: "Colossians 3:13" },
      { text: "For if you forgive other people when they sin against you, your heavenly Father will also forgive you.", ref: "Matthew 6:14" },
      { text: "He has not dealt with us according to our sins, nor punished us according to our iniquities.", ref: "Psalm 103:10" },
      { text: "As far as the east is from the west, so far has he removed our transgressions from us.", ref: "Psalm 103:12" },
    ],
  },
  {
    id: 'wisdom', icon: '📖', color: '#d35400',
    verses: [
      { text: "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you.", ref: "James 1:5" },
      { text: "The fear of the Lord is the beginning of wisdom; all who follow his precepts have good understanding.", ref: "Psalm 111:10" },
      { text: "Your word is a lamp for my feet, a light on my path.", ref: "Psalm 119:105" },
      { text: "All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness.", ref: "2 Timothy 3:16" },
      { text: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind.", ref: "Romans 12:2" },
    ],
  },
  {
    id: 'comfort', icon: '🛡️', color: '#7f8c8d',
    verses: [
      { text: "Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.", ref: "Psalm 23:4" },
      { text: "God is our refuge and strength, an ever-present help in trouble.", ref: "Psalm 46:1" },
      { text: "Cast all your anxiety on him because he cares for you.", ref: "1 Peter 5:7" },
      { text: "He heals the brokenhearted and binds up their wounds.", ref: "Psalm 147:3" },
      { text: "Blessed are those who mourn, for they will be comforted.", ref: "Matthew 5:4" },
    ],
  },
];

// Crisis helplines by language
export const CRISIS_LINES = {
  en: { number: '988', name: 'Suicide & Crisis Lifeline', region: 'USA' },
  es: { number: '024', name: 'Línea de Atención a Conducta Suicida', region: 'España/LATAM' },
  pt: { number: '141', name: 'CVV - Centro de Valorização da Vida', region: 'Brasil' },
  it: { number: '800 274 274', name: 'Telefono Amico', region: 'Italia' },
  pl: { number: '116 123', name: 'Telefon Zaufania', region: 'Polska' },
  de: { number: '0800 111 0 111', name: 'Telefonseelsorge', region: 'Deutschland' },
  fr: { number: '3114', name: 'Numéro National de Prévention du Suicide', region: 'France' },
  ru: { number: '8-800-2000-122', name: 'Телефон доверия', region: 'Россия' },
  ro: { number: '0800 801 200', name: 'Linia Verde de Sănătate Mintală', region: 'România' },
  sk: { number: '0800 500 333', name: 'Linka nádeje', region: 'Slovensko' },
};

// ─── UI Translations ─────────────────────────────────────────────────────────

export const T = {
  en: {
    appName: 'Thank You Jesus',
    appTagline: 'Your companion for life\'s journey',
    selectLanguage: 'Choose your language',
    selectDenomination: 'What is your faith background?',
    continue: 'Continue',
    back: 'Back',
    // Denominations
    catholic: 'Catholic', catholicDesc: 'Roman Catholic tradition',
    orthodox: 'Orthodox', orthodoxDesc: 'Eastern Orthodox tradition',
    protestant: 'Protestant / Evangelical', protestantDesc: 'Reformed & Evangelical tradition',
    ecumenical: 'Ecumenical', ecumenicalDesc: 'Shared Christian foundation',
    seeker: 'Seeker / Explorer', seekerDesc: 'Curious about faith',
    // Disclaimer
    disclaimerTitle: 'A word before we begin',
    disclaimerText: 'Thank You Jesus is an AI-powered app inspired by the Bible and the teachings of Jesus Christ. It is not a replacement for prayer, the Church, a pastor, or a priest. Responses are generated by artificial intelligence and may not be perfect. Always seek guidance from your faith community. In a crisis, please contact a real person.',
    disclaimerAgree: 'I understand — let\'s begin',
    // Home
    greeting_morning: 'Good morning',
    greeting_afternoon: 'Good afternoon',
    greeting_evening: 'Good evening',
    dailyVerse: 'Verse of the Day',
    quickTopics: 'What\'s on your heart?',
    openBible: 'Open the Bible',
    // Topics
    grief: 'Grief', fear: 'Fear', decision: 'Decision', forgiveness: 'Forgiveness',
    gratitude: 'Gratitude', love: 'Love', temptation: 'Temptation', hope: 'Hope',
    // Chat
    chatTitle: 'Talk with Jesus',
    chatPlaceholder: 'Share what\'s on your heart...',
    chatSend: 'Send',
    chatWelcome: 'Peace be with you. What is on your heart today?',
    chatTyping: 'Jesus is listening...',
    freeMessages: 'free messages remaining today',
    upgradeToPremium: 'Upgrade to Premium',
    premiumBenefits: 'Unlimited conversations · No ads · All features',
    // Bible
    bibleTitle: 'Holy Bible',
    bibleSearch: 'Search',
    bibleSearchPlaceholder: 'Search by topic, verse reference...',
    bibleTopics: 'Topics',
    noResults: 'No results found. Try a different search.',
    // Prayer
    prayerTitle: 'Prayer Room',
    prayerAdd: 'Add prayer intention',
    prayerPlaceholder: 'What would you like to pray for?',
    prayerAnswered: 'Mark as answered',
    prayerEmpty: 'Your prayer room is empty. Add your first intention above.',
    // Journal
    journalTitle: 'Spiritual Journal',
    journalAdd: 'New entry',
    journalPlaceholder: 'Write your thoughts, reflections, and prayers...',
    journalEmpty: 'Your journal is empty. Start writing your spiritual journey.',
    // Favorites
    favoritesTitle: 'Saved Verses',
    favoritesEmpty: 'No saved verses yet. Tap ⭐ on any verse to save it here.',
    // Settings
    settingsTitle: 'Settings',
    settingsLanguage: 'Language',
    settingsDenomination: 'Faith background',
    settingsAbout: 'About',
    settingsPrivacy: 'Privacy Policy',
    settingsVersion: 'Version 1.0.0',
    // Premium
    premiumTitle: 'Thank You Jesus Premium',
    premiumSubtitle: 'Unlimited access to all features',
    premiumPrice: '$4.99 / month',
    premiumYearly: '$39.99 / year (save 33%)',
    premiumFeature1: '✓ Unlimited conversations with Jesus',
    premiumFeature2: '✓ No advertisements',
    premiumFeature3: '✓ Prayer journal & history',
    premiumFeature4: '✓ Bible reading plans',
    premiumFeature5: '✓ Offline access',
    premiumCTA: 'Start Premium',
    premiumRestore: 'Restore purchase',
    premiumCancel: 'Not now',
    // Nav
    navHome: 'Home', navChat: 'Talk', navBible: 'Bible', navPrayer: 'Prayer', navMore: 'More',
    // Crisis
    crisisDetected: 'I hear that you\'re going through something very difficult. You are not alone, and there is always hope. Please reach out to someone who can help right now:',
    crisisCall: 'Call Crisis Line',
    crisisContinue: 'Continue conversation',
  },

  es: {
    appName: 'Thank You Jesus',
    appTagline: 'Tu compañero en el camino de la vida',
    selectLanguage: 'Elige tu idioma',
    selectDenomination: '¿Cuál es tu tradición de fe?',
    continue: 'Continuar',
    back: 'Atrás',
    catholic: 'Católico', catholicDesc: 'Tradición Católica Romana',
    orthodox: 'Ortodoxo', orthodoxDesc: 'Tradición Ortodoxa Oriental',
    protestant: 'Protestante / Evangélico', protestantDesc: 'Tradición Reformada',
    ecumenical: 'Ecuménico', ecumenicalDesc: 'Base cristiana común',
    seeker: 'Buscador', seekerDesc: 'Curioso sobre la fe',
    disclaimerTitle: 'Antes de comenzar',
    disclaimerText: 'Thank You Jesus es una app de IA inspirada en la Biblia. No reemplaza la oración, la Iglesia, ni un pastor. Las respuestas son generadas por inteligencia artificial. En una crisis, contacta a una persona real.',
    disclaimerAgree: 'Entiendo — empecemos',
    greeting_morning: 'Buenos días', greeting_afternoon: 'Buenas tardes', greeting_evening: 'Buenas noches',
    dailyVerse: 'Versículo del Día',
    quickTopics: '¿Qué hay en tu corazón?',
    openBible: 'Abrir la Biblia',
    grief: 'Dolor', fear: 'Miedo', decision: 'Decisión', forgiveness: 'Perdón',
    gratitude: 'Gratitud', love: 'Amor', temptation: 'Tentación', hope: 'Esperanza',
    chatTitle: 'Habla con Jesús',
    chatPlaceholder: 'Comparte lo que hay en tu corazón...',
    chatSend: 'Enviar',
    chatWelcome: 'La paz sea contigo. ¿Qué hay en tu corazón hoy?',
    chatTyping: 'Jesús está escuchando...',
    freeMessages: 'mensajes gratuitos restantes hoy',
    upgradeToPremium: 'Actualizar a Premium',
    premiumBenefits: 'Conversaciones ilimitadas · Sin anuncios · Todo incluido',
    bibleTitle: 'Santa Biblia',
    bibleSearch: 'Buscar',
    bibleSearchPlaceholder: 'Busca por tema o referencia...',
    bibleTopics: 'Temas',
    noResults: 'Sin resultados. Intenta otra búsqueda.',
    prayerTitle: 'Sala de Oración',
    prayerAdd: 'Añadir intención',
    prayerPlaceholder: '¿Por qué quieres orar?',
    prayerAnswered: 'Marcar como respondida',
    prayerEmpty: 'Tu sala de oración está vacía.',
    journalTitle: 'Diario Espiritual',
    journalAdd: 'Nueva entrada',
    journalPlaceholder: 'Escribe tus pensamientos...',
    journalEmpty: 'Tu diario está vacío.',
    favoritesTitle: 'Versículos Guardados',
    favoritesEmpty: 'Aún no hay versículos guardados.',
    settingsTitle: 'Ajustes', settingsLanguage: 'Idioma', settingsDenomination: 'Tradición de fe',
    settingsAbout: 'Acerca de', settingsPrivacy: 'Política de Privacidad', settingsVersion: 'Versión 1.0.0',
    premiumTitle: 'Thank You Jesus Premium',
    premiumSubtitle: 'Acceso ilimitado a todas las funciones',
    premiumPrice: '$4.99 / mes', premiumYearly: '$39.99 / año (ahorra 33%)',
    premiumFeature1: '✓ Conversaciones ilimitadas', premiumFeature2: '✓ Sin publicidad',
    premiumFeature3: '✓ Diario de oración', premiumFeature4: '✓ Planes de lectura bíblica',
    premiumFeature5: '✓ Acceso sin conexión',
    premiumCTA: 'Iniciar Premium', premiumRestore: 'Restaurar compra', premiumCancel: 'Ahora no',
    navHome: 'Inicio', navChat: 'Hablar', navBible: 'Biblia', navPrayer: 'Oración', navMore: 'Más',
    crisisDetected: 'Escucho que estás pasando por algo muy difícil. No estás solo/a, y siempre hay esperanza. Por favor, comunícate con alguien que pueda ayudarte ahora:',
    crisisCall: 'Llamar a la Línea de Crisis', crisisContinue: 'Continuar conversación',
  },

  pt: {
    appName: 'Thank You Jesus',
    appTagline: 'Seu companheiro na jornada da vida',
    selectLanguage: 'Escolha seu idioma',
    selectDenomination: 'Qual é a sua tradição de fé?',
    continue: 'Continuar', back: 'Voltar',
    catholic: 'Católico', catholicDesc: 'Tradição Católica Romana',
    orthodox: 'Ortodoxo', orthodoxDesc: 'Tradição Ortodoxa Oriental',
    protestant: 'Protestante / Evangélico', protestantDesc: 'Tradição Reformada',
    ecumenical: 'Ecumênico', ecumenicalDesc: 'Base cristã comum',
    seeker: 'Buscador', seekerDesc: 'Curioso sobre a fé',
    disclaimerTitle: 'Uma palavra antes de começar',
    disclaimerText: 'Thank You Jesus é um app de IA inspirado na Bíblia. Não substitui a oração, a Igreja ou um pastor. Em uma crise, entre em contato com uma pessoa real.',
    disclaimerAgree: 'Entendi — vamos começar',
    greeting_morning: 'Bom dia', greeting_afternoon: 'Boa tarde', greeting_evening: 'Boa noite',
    dailyVerse: 'Versículo do Dia',
    quickTopics: 'O que está em seu coração?',
    openBible: 'Abrir a Bíblia',
    grief: 'Dor', fear: 'Medo', decision: 'Decisão', forgiveness: 'Perdão',
    gratitude: 'Gratidão', love: 'Amor', temptation: 'Tentação', hope: 'Esperança',
    chatTitle: 'Fale com Jesus', chatPlaceholder: 'Compartilhe o que está em seu coração...', chatSend: 'Enviar',
    chatWelcome: 'A paz esteja com você. O que está em seu coração hoje?', chatTyping: 'Jesus está ouvindo...',
    freeMessages: 'mensagens gratuitas restantes hoje', upgradeToPremium: 'Atualizar para Premium',
    premiumBenefits: 'Conversas ilimitadas · Sem anúncios · Tudo incluído',
    bibleTitle: 'Sagrada Bíblia', bibleSearch: 'Buscar', bibleSearchPlaceholder: 'Buscar por tema ou referência...',
    bibleTopics: 'Tópicos', noResults: 'Nenhum resultado. Tente outra busca.',
    prayerTitle: 'Sala de Oração', prayerAdd: 'Adicionar intenção', prayerPlaceholder: 'Pelo que você quer orar?',
    prayerAnswered: 'Marcar como respondida', prayerEmpty: 'Sua sala de oração está vazia.',
    journalTitle: 'Diário Espiritual', journalAdd: 'Nova entrada', journalPlaceholder: 'Escreva seus pensamentos...',
    journalEmpty: 'Seu diário está vazio.',
    favoritesTitle: 'Versículos Salvos', favoritesEmpty: 'Nenhum versículo salvo ainda.',
    settingsTitle: 'Configurações', settingsLanguage: 'Idioma', settingsDenomination: 'Tradição de fé',
    settingsAbout: 'Sobre', settingsPrivacy: 'Política de Privacidade', settingsVersion: 'Versão 1.0.0',
    premiumTitle: 'Thank You Jesus Premium', premiumSubtitle: 'Acesso ilimitado a todos os recursos',
    premiumPrice: '$4.99 / mês', premiumYearly: '$39.99 / ano (economize 33%)',
    premiumFeature1: '✓ Conversas ilimitadas', premiumFeature2: '✓ Sem publicidade',
    premiumFeature3: '✓ Diário de oração', premiumFeature4: '✓ Planos de leitura bíblica',
    premiumFeature5: '✓ Acesso offline',
    premiumCTA: 'Iniciar Premium', premiumRestore: 'Restaurar compra', premiumCancel: 'Agora não',
    navHome: 'Início', navChat: 'Conversar', navBible: 'Bíblia', navPrayer: 'Oração', navMore: 'Mais',
    crisisDetected: 'Percebo que você está passando por algo muito difícil. Você não está sozinho/a. Por favor, entre em contato com alguém que possa ajudar agora:',
    crisisCall: 'Ligar para a Linha de Crise', crisisContinue: 'Continuar conversa',
  },

  it: {
    appName: 'Thank You Jesus',
    appTagline: 'Il tuo compagno nel cammino della vita',
    selectLanguage: 'Scegli la tua lingua',
    selectDenomination: 'Qual è la tua tradizione di fede?',
    continue: 'Continua', back: 'Indietro',
    catholic: 'Cattolico', catholicDesc: 'Tradizione Cattolica Romana',
    orthodox: 'Ortodosso', orthodoxDesc: 'Tradizione Ortodossa Orientale',
    protestant: 'Protestante / Evangelico', protestantDesc: 'Tradizione Riformata',
    ecumenical: 'Ecumenico', ecumenicalDesc: 'Base cristiana comune',
    seeker: 'Cercatore', seekerDesc: 'Curioso della fede',
    disclaimerTitle: 'Una parola prima di iniziare',
    disclaimerText: 'Thank You Jesus è un\'app AI ispirata alla Bibbia. Non sostituisce la preghiera, la Chiesa o un sacerdote. In una crisi, contatta una persona reale.',
    disclaimerAgree: 'Ho capito — iniziamo',
    greeting_morning: 'Buongiorno', greeting_afternoon: 'Buon pomeriggio', greeting_evening: 'Buonasera',
    dailyVerse: 'Versetto del Giorno', quickTopics: 'Cosa c\'è nel tuo cuore?', openBible: 'Apri la Bibbia',
    grief: 'Dolore', fear: 'Paura', decision: 'Decisione', forgiveness: 'Perdono',
    gratitude: 'Gratitudine', love: 'Amore', temptation: 'Tentazione', hope: 'Speranza',
    chatTitle: 'Parla con Gesù', chatPlaceholder: 'Condividi ciò che hai nel cuore...', chatSend: 'Invia',
    chatWelcome: 'La pace sia con te. Cosa c\'è nel tuo cuore oggi?', chatTyping: 'Gesù sta ascoltando...',
    freeMessages: 'messaggi gratuiti rimanenti oggi', upgradeToPremium: 'Passa a Premium',
    premiumBenefits: 'Conversazioni illimitate · Nessuna pubblicità · Tutto incluso',
    bibleTitle: 'Santa Bibbia', bibleSearch: 'Cerca', bibleSearchPlaceholder: 'Cerca per argomento o riferimento...',
    bibleTopics: 'Argomenti', noResults: 'Nessun risultato. Prova un\'altra ricerca.',
    prayerTitle: 'Stanza della Preghiera', prayerAdd: 'Aggiungi intenzione', prayerPlaceholder: 'Per cosa vuoi pregare?',
    prayerAnswered: 'Segna come esaudita', prayerEmpty: 'La tua stanza di preghiera è vuota.',
    journalTitle: 'Diario Spirituale', journalAdd: 'Nuova voce', journalPlaceholder: 'Scrivi i tuoi pensieri...',
    journalEmpty: 'Il tuo diario è vuoto.',
    favoritesTitle: 'Versetti Salvati', favoritesEmpty: 'Nessun versetto salvato.',
    settingsTitle: 'Impostazioni', settingsLanguage: 'Lingua', settingsDenomination: 'Tradizione di fede',
    settingsAbout: 'Info', settingsPrivacy: 'Privacy', settingsVersion: 'Versione 1.0.0',
    premiumTitle: 'Thank You Jesus Premium', premiumSubtitle: 'Accesso illimitato a tutte le funzioni',
    premiumPrice: '$4.99 / mese', premiumYearly: '$39.99 / anno (risparmia 33%)',
    premiumFeature1: '✓ Conversazioni illimitate', premiumFeature2: '✓ Nessuna pubblicità',
    premiumFeature3: '✓ Diario di preghiera', premiumFeature4: '✓ Piani di lettura biblica',
    premiumFeature5: '✓ Accesso offline',
    premiumCTA: 'Inizia Premium', premiumRestore: 'Ripristina acquisto', premiumCancel: 'Non ora',
    navHome: 'Home', navChat: 'Parla', navBible: 'Bibbia', navPrayer: 'Preghiera', navMore: 'Altro',
    crisisDetected: 'Sento che stai attraversando qualcosa di molto difficile. Non sei solo/a. Per favore, contatta qualcuno che possa aiutarti ora:',
    crisisCall: 'Chiama la Linea di Crisi', crisisContinue: 'Continua la conversazione',
  },

  pl: {
    appName: 'Thank You Jesus',
    appTagline: 'Twój towarzysz w drodze życia',
    selectLanguage: 'Wybierz swój język',
    selectDenomination: 'Jaka jest Twoja tradycja wiary?',
    continue: 'Dalej', back: 'Wróć',
    catholic: 'Katolik', catholicDesc: 'Tradycja Katolicka',
    orthodox: 'Prawosławny', orthodoxDesc: 'Tradycja Prawosławna',
    protestant: 'Protestant / Ewangelik', protestantDesc: 'Tradycja Reformowana',
    ecumenical: 'Ekumeniczny', ecumenicalDesc: 'Wspólna podstawa chrześcijańska',
    seeker: 'Poszukujący', seekerDesc: 'Ciekawy wiary',
    disclaimerTitle: 'Słowo przed rozpoczęciem',
    disclaimerText: 'Thank You Jesus to aplikacja AI inspirowana Biblią. Nie zastępuje modlitwy, Kościoła ani kapłana. W kryzysie skontaktuj się z prawdziwą osobą.',
    disclaimerAgree: 'Rozumiem — zaczynamy',
    greeting_morning: 'Dzień dobry', greeting_afternoon: 'Dzień dobry', greeting_evening: 'Dobry wieczór',
    dailyVerse: 'Werset Dnia', quickTopics: 'Co masz w sercu?', openBible: 'Otwórz Biblię',
    grief: 'Żal', fear: 'Strach', decision: 'Decyzja', forgiveness: 'Przebaczenie',
    gratitude: 'Wdzięczność', love: 'Miłość', temptation: 'Pokusa', hope: 'Nadzieja',
    chatTitle: 'Rozmawiaj z Jezusem', chatPlaceholder: 'Podziel się tym, co masz w sercu...', chatSend: 'Wyślij',
    chatWelcome: 'Pokój niech będzie z tobą. Co masz w sercu dzisiaj?', chatTyping: 'Jezus słucha...',
    freeMessages: 'darmowych wiadomości pozostało dzisiaj', upgradeToPremium: 'Przejdź na Premium',
    premiumBenefits: 'Nieograniczone rozmowy · Bez reklam · Wszystko włączone',
    bibleTitle: 'Pismo Święte', bibleSearch: 'Szukaj', bibleSearchPlaceholder: 'Szukaj tematu lub wersetu...',
    bibleTopics: 'Tematy', noResults: 'Brak wyników. Spróbuj innego wyszukiwania.',
    prayerTitle: 'Pokój Modlitwy', prayerAdd: 'Dodaj intencję', prayerPlaceholder: 'O co chcesz się modlić?',
    prayerAnswered: 'Oznacz jako wysłuchaną', prayerEmpty: 'Twój pokój modlitwy jest pusty.',
    journalTitle: 'Duchowy Dziennik', journalAdd: 'Nowy wpis', journalPlaceholder: 'Zapisz swoje myśli...',
    journalEmpty: 'Twój dziennik jest pusty.',
    favoritesTitle: 'Zapisane Wersety', favoritesEmpty: 'Brak zapisanych wersetów.',
    settingsTitle: 'Ustawienia', settingsLanguage: 'Język', settingsDenomination: 'Tradycja wiary',
    settingsAbout: 'O aplikacji', settingsPrivacy: 'Polityka prywatności', settingsVersion: 'Wersja 1.0.0',
    premiumTitle: 'Thank You Jesus Premium', premiumSubtitle: 'Nieograniczony dostęp do wszystkich funkcji',
    premiumPrice: '$4.99 / miesiąc', premiumYearly: '$39.99 / rok (oszczędź 33%)',
    premiumFeature1: '✓ Nieograniczone rozmowy', premiumFeature2: '✓ Bez reklam',
    premiumFeature3: '✓ Dziennik modlitwy', premiumFeature4: '✓ Plany czytania Biblii',
    premiumFeature5: '✓ Dostęp offline',
    premiumCTA: 'Rozpocznij Premium', premiumRestore: 'Przywróć zakup', premiumCancel: 'Nie teraz',
    navHome: 'Dom', navChat: 'Rozmowa', navBible: 'Biblia', navPrayer: 'Modlitwa', navMore: 'Więcej',
    crisisDetected: 'Słyszę, że przeżywasz coś bardzo trudnego. Nie jesteś sam/a. Proszę, skontaktuj się teraz z kimś, kto może pomóc:',
    crisisCall: 'Zadzwoń na Linię Kryzysową', crisisContinue: 'Kontynuuj rozmowę',
  },

  de: {
    appName: 'Thank You Jesus',
    appTagline: 'Dein Begleiter auf dem Weg des Lebens',
    selectLanguage: 'Wähle deine Sprache',
    selectDenomination: 'Was ist deine Glaubenstradition?',
    continue: 'Weiter', back: 'Zurück',
    catholic: 'Katholisch', catholicDesc: 'Römisch-Katholische Tradition',
    orthodox: 'Orthodox', orthodoxDesc: 'Ostorthodoxe Tradition',
    protestant: 'Protestantisch / Evangelisch', protestantDesc: 'Reformierte Tradition',
    ecumenical: 'Ökumenisch', ecumenicalDesc: 'Gemeinsame christliche Grundlage',
    seeker: 'Suchender', seekerDesc: 'Neugierig auf den Glauben',
    disclaimerTitle: 'Ein Wort bevor wir beginnen',
    disclaimerText: 'Thank You Jesus ist eine KI-App, inspiriert von der Bibel. Sie ersetzt nicht das Gebet, die Kirche oder einen Pfarrer. In einer Krise, wende dich an eine echte Person.',
    disclaimerAgree: 'Ich verstehe — los geht\'s',
    greeting_morning: 'Guten Morgen', greeting_afternoon: 'Guten Tag', greeting_evening: 'Guten Abend',
    dailyVerse: 'Tagesvers', quickTopics: 'Was liegt dir auf dem Herzen?', openBible: 'Bibel öffnen',
    grief: 'Trauer', fear: 'Angst', decision: 'Entscheidung', forgiveness: 'Vergebung',
    gratitude: 'Dankbarkeit', love: 'Liebe', temptation: 'Versuchung', hope: 'Hoffnung',
    chatTitle: 'Mit Jesus sprechen', chatPlaceholder: 'Teile, was dich bewegt...', chatSend: 'Senden',
    chatWelcome: 'Friede sei mit dir. Was liegt dir heute auf dem Herzen?', chatTyping: 'Jesus hört zu...',
    freeMessages: 'kostenlose Nachrichten verbleiben heute', upgradeToPremium: 'Auf Premium upgraden',
    premiumBenefits: 'Unbegrenzte Gespräche · Keine Werbung · Alles inklusive',
    bibleTitle: 'Heilige Bibel', bibleSearch: 'Suchen', bibleSearchPlaceholder: 'Nach Thema oder Vers suchen...',
    bibleTopics: 'Themen', noResults: 'Keine Ergebnisse. Versuche eine andere Suche.',
    prayerTitle: 'Gebetsraum', prayerAdd: 'Gebetsanliegen hinzufügen', prayerPlaceholder: 'Wofür möchtest du beten?',
    prayerAnswered: 'Als erhört markieren', prayerEmpty: 'Dein Gebetsraum ist leer.',
    journalTitle: 'Geistliches Tagebuch', journalAdd: 'Neuer Eintrag', journalPlaceholder: 'Schreibe deine Gedanken...',
    journalEmpty: 'Dein Tagebuch ist leer.',
    favoritesTitle: 'Gespeicherte Verse', favoritesEmpty: 'Noch keine gespeicherten Verse.',
    settingsTitle: 'Einstellungen', settingsLanguage: 'Sprache', settingsDenomination: 'Glaubenstradition',
    settingsAbout: 'Über', settingsPrivacy: 'Datenschutz', settingsVersion: 'Version 1.0.0',
    premiumTitle: 'Thank You Jesus Premium', premiumSubtitle: 'Unbegrenzter Zugang zu allen Funktionen',
    premiumPrice: '$4.99 / Monat', premiumYearly: '$39.99 / Jahr (spare 33%)',
    premiumFeature1: '✓ Unbegrenzte Gespräche', premiumFeature2: '✓ Keine Werbung',
    premiumFeature3: '✓ Gebetstagebuch', premiumFeature4: '✓ Bibellesepläne',
    premiumFeature5: '✓ Offline-Zugang',
    premiumCTA: 'Premium starten', premiumRestore: 'Kauf wiederherstellen', premiumCancel: 'Nicht jetzt',
    navHome: 'Start', navChat: 'Sprechen', navBible: 'Bibel', navPrayer: 'Gebet', navMore: 'Mehr',
    crisisDetected: 'Ich höre, dass du etwas sehr Schwieriges durchmachst. Du bist nicht allein. Bitte wende dich jetzt an jemanden, der helfen kann:',
    crisisCall: 'Krisenhotline anrufen', crisisContinue: 'Gespräch fortsetzen',
  },

  fr: {
    appName: 'Thank You Jesus',
    appTagline: 'Votre compagnon sur le chemin de la vie',
    selectLanguage: 'Choisissez votre langue',
    selectDenomination: 'Quelle est votre tradition de foi?',
    continue: 'Continuer', back: 'Retour',
    catholic: 'Catholique', catholicDesc: 'Tradition Catholique Romaine',
    orthodox: 'Orthodoxe', orthodoxDesc: 'Tradition Orthodoxe Orientale',
    protestant: 'Protestant / Évangélique', protestantDesc: 'Tradition Réformée',
    ecumenical: 'Œcuménique', ecumenicalDesc: 'Base chrétienne commune',
    seeker: 'Chercheur', seekerDesc: 'Curieux de la foi',
    disclaimerTitle: 'Un mot avant de commencer',
    disclaimerText: 'Thank You Jesus est une app IA inspirée par la Bible. Elle ne remplace pas la prière, l\'Église ou un pasteur. En cas de crise, contactez une personne réelle.',
    disclaimerAgree: 'Je comprends — commençons',
    greeting_morning: 'Bonjour', greeting_afternoon: 'Bonjour', greeting_evening: 'Bonsoir',
    dailyVerse: 'Verset du Jour', quickTopics: 'Qu\'y a-t-il dans votre cœur?', openBible: 'Ouvrir la Bible',
    grief: 'Deuil', fear: 'Peur', decision: 'Décision', forgiveness: 'Pardon',
    gratitude: 'Gratitude', love: 'Amour', temptation: 'Tentation', hope: 'Espérance',
    chatTitle: 'Parlez avec Jésus', chatPlaceholder: 'Partagez ce qui est dans votre cœur...', chatSend: 'Envoyer',
    chatWelcome: 'La paix soit avec vous. Qu\'y a-t-il dans votre cœur aujourd\'hui?', chatTyping: 'Jésus écoute...',
    freeMessages: 'messages gratuits restants aujourd\'hui', upgradeToPremium: 'Passer à Premium',
    premiumBenefits: 'Conversations illimitées · Sans publicité · Tout inclus',
    bibleTitle: 'Sainte Bible', bibleSearch: 'Rechercher', bibleSearchPlaceholder: 'Rechercher par thème ou référence...',
    bibleTopics: 'Thèmes', noResults: 'Aucun résultat. Essayez une autre recherche.',
    prayerTitle: 'Salle de Prière', prayerAdd: 'Ajouter une intention', prayerPlaceholder: 'Pour quoi voulez-vous prier?',
    prayerAnswered: 'Marquer comme exaucée', prayerEmpty: 'Votre salle de prière est vide.',
    journalTitle: 'Journal Spirituel', journalAdd: 'Nouvelle entrée', journalPlaceholder: 'Écrivez vos pensées...',
    journalEmpty: 'Votre journal est vide.',
    favoritesTitle: 'Versets Sauvegardés', favoritesEmpty: 'Aucun verset sauvegardé.',
    settingsTitle: 'Paramètres', settingsLanguage: 'Langue', settingsDenomination: 'Tradition de foi',
    settingsAbout: 'À propos', settingsPrivacy: 'Confidentialité', settingsVersion: 'Version 1.0.0',
    premiumTitle: 'Thank You Jesus Premium', premiumSubtitle: 'Accès illimité à toutes les fonctions',
    premiumPrice: '$4.99 / mois', premiumYearly: '$39.99 / an (économisez 33%)',
    premiumFeature1: '✓ Conversations illimitées', premiumFeature2: '✓ Sans publicité',
    premiumFeature3: '✓ Journal de prière', premiumFeature4: '✓ Plans de lecture biblique',
    premiumFeature5: '✓ Accès hors ligne',
    premiumCTA: 'Démarrer Premium', premiumRestore: 'Restaurer l\'achat', premiumCancel: 'Pas maintenant',
    navHome: 'Accueil', navChat: 'Parler', navBible: 'Bible', navPrayer: 'Prière', navMore: 'Plus',
    crisisDetected: 'J\'entends que vous traversez quelque chose de très difficile. Vous n\'êtes pas seul(e). Veuillez contacter quelqu\'un qui peut vous aider maintenant:',
    crisisCall: 'Appeler la Ligne de Crise', crisisContinue: 'Continuer la conversation',
  },

  ru: {
    appName: 'Thank You Jesus',
    appTagline: 'Ваш спутник на жизненном пути',
    selectLanguage: 'Выберите язык',
    selectDenomination: 'Какова ваша религиозная традиция?',
    continue: 'Продолжить', back: 'Назад',
    catholic: 'Католик', catholicDesc: 'Римско-католическая традиция',
    orthodox: 'Православный', orthodoxDesc: 'Православная традиция',
    protestant: 'Протестант / Евангелист', protestantDesc: 'Реформатская традиция',
    ecumenical: 'Экуменический', ecumenicalDesc: 'Общая христианская основа',
    seeker: 'Ищущий', seekerDesc: 'Интересующийся верой',
    disclaimerTitle: 'Слово перед началом',
    disclaimerText: 'Thank You Jesus — приложение с ИИ, вдохновлённое Библией. Оно не заменяет молитву, Церковь или священника. В кризисной ситуации обратитесь к реальному человеку.',
    disclaimerAgree: 'Понимаю — начнём',
    greeting_morning: 'Доброе утро', greeting_afternoon: 'Добрый день', greeting_evening: 'Добрый вечер',
    dailyVerse: 'Стих Дня', quickTopics: 'Что у вас на сердце?', openBible: 'Открыть Библию',
    grief: 'Горе', fear: 'Страх', decision: 'Решение', forgiveness: 'Прощение',
    gratitude: 'Благодарность', love: 'Любовь', temptation: 'Искушение', hope: 'Надежда',
    chatTitle: 'Поговорите с Иисусом', chatPlaceholder: 'Поделитесь тем, что на сердце...', chatSend: 'Отправить',
    chatWelcome: 'Мир вам. Что у вас на сердце сегодня?', chatTyping: 'Иисус слушает...',
    freeMessages: 'бесплатных сообщений осталось сегодня', upgradeToPremium: 'Перейти на Premium',
    premiumBenefits: 'Неограниченные разговоры · Без рекламы · Всё включено',
    bibleTitle: 'Священное Писание', bibleSearch: 'Поиск', bibleSearchPlaceholder: 'Поиск по теме или ссылке...',
    bibleTopics: 'Темы', noResults: 'Ничего не найдено. Попробуйте другой запрос.',
    prayerTitle: 'Молитвенная комната', prayerAdd: 'Добавить намерение', prayerPlaceholder: 'О чём вы хотите молиться?',
    prayerAnswered: 'Отметить как услышанную', prayerEmpty: 'Ваша молитвенная комната пуста.',
    journalTitle: 'Духовный дневник', journalAdd: 'Новая запись', journalPlaceholder: 'Запишите свои мысли...',
    journalEmpty: 'Ваш дневник пуст.',
    favoritesTitle: 'Сохранённые стихи', favoritesEmpty: 'Нет сохранённых стихов.',
    settingsTitle: 'Настройки', settingsLanguage: 'Язык', settingsDenomination: 'Религиозная традиция',
    settingsAbout: 'О приложении', settingsPrivacy: 'Конфиденциальность', settingsVersion: 'Версия 1.0.0',
    premiumTitle: 'Thank You Jesus Premium', premiumSubtitle: 'Неограниченный доступ ко всем функциям',
    premiumPrice: '$4.99 / месяц', premiumYearly: '$39.99 / год (экономия 33%)',
    premiumFeature1: '✓ Неограниченные разговоры', premiumFeature2: '✓ Без рекламы',
    premiumFeature3: '✓ Дневник молитв', premiumFeature4: '✓ Планы чтения Библии',
    premiumFeature5: '✓ Офлайн-доступ',
    premiumCTA: 'Начать Premium', premiumRestore: 'Восстановить покупку', premiumCancel: 'Не сейчас',
    navHome: 'Главная', navChat: 'Говорить', navBible: 'Библия', navPrayer: 'Молитва', navMore: 'Ещё',
    crisisDetected: 'Я слышу, что вы переживаете что-то очень трудное. Вы не одни. Пожалуйста, обратитесь к тому, кто может помочь прямо сейчас:',
    crisisCall: 'Позвонить на линию помощи', crisisContinue: 'Продолжить разговор',
  },

  ro: {
    appName: 'Thank You Jesus',
    appTagline: 'Însoțitorul tău pe drumul vieții',
    selectLanguage: 'Alege limba ta',
    selectDenomination: 'Care este tradiția ta de credință?',
    continue: 'Continuă', back: 'Înapoi',
    catholic: 'Catolic', catholicDesc: 'Tradiția Catolică Romană',
    orthodox: 'Ortodox', orthodoxDesc: 'Tradiția Ortodoxă Răsăriteană',
    protestant: 'Protestant / Evanghelic', protestantDesc: 'Tradiția Reformată',
    ecumenical: 'Ecumenic', ecumenicalDesc: 'Baza creștină comună',
    seeker: 'Căutător', seekerDesc: 'Curios despre credință',
    disclaimerTitle: 'Un cuvânt înainte de a începe',
    disclaimerText: 'Thank You Jesus este o aplicație AI inspirată din Biblie. Nu înlocuiește rugăciunea, Biserica sau un preot. Într-o criză, contactați o persoană reală.',
    disclaimerAgree: 'Înțeleg — să începem',
    greeting_morning: 'Bună dimineața', greeting_afternoon: 'Bună ziua', greeting_evening: 'Bună seara',
    dailyVerse: 'Versetul Zilei', quickTopics: 'Ce ai pe inimă?', openBible: 'Deschide Biblia',
    grief: 'Durere', fear: 'Frică', decision: 'Decizie', forgiveness: 'Iertare',
    gratitude: 'Recunoștință', love: 'Iubire', temptation: 'Ispită', hope: 'Speranță',
    chatTitle: 'Vorbește cu Isus', chatPlaceholder: 'Împărtășește ce ai pe inimă...', chatSend: 'Trimite',
    chatWelcome: 'Pace ție. Ce ai pe inimă astăzi?', chatTyping: 'Isus ascultă...',
    freeMessages: 'mesaje gratuite rămase astăzi', upgradeToPremium: 'Treceți la Premium',
    premiumBenefits: 'Conversații nelimitate · Fără reclame · Tot inclus',
    bibleTitle: 'Sfânta Biblie', bibleSearch: 'Caută', bibleSearchPlaceholder: 'Caută după temă sau referință...',
    bibleTopics: 'Teme', noResults: 'Niciun rezultat. Încearcă altă căutare.',
    prayerTitle: 'Camera de Rugăciune', prayerAdd: 'Adaugă intenție', prayerPlaceholder: 'Pentru ce vrei să te rogi?',
    prayerAnswered: 'Marchează ca răspunsă', prayerEmpty: 'Camera ta de rugăciune este goală.',
    journalTitle: 'Jurnal Spiritual', journalAdd: 'Intrare nouă', journalPlaceholder: 'Scrie gândurile tale...',
    journalEmpty: 'Jurnalul tău este gol.',
    favoritesTitle: 'Versete Salvate', favoritesEmpty: 'Niciun verset salvat.',
    settingsTitle: 'Setări', settingsLanguage: 'Limbă', settingsDenomination: 'Tradiție de credință',
    settingsAbout: 'Despre', settingsPrivacy: 'Confidențialitate', settingsVersion: 'Versiunea 1.0.0',
    premiumTitle: 'Thank You Jesus Premium', premiumSubtitle: 'Acces nelimitat la toate funcțiile',
    premiumPrice: '$4.99 / lună', premiumYearly: '$39.99 / an (economisești 33%)',
    premiumFeature1: '✓ Conversații nelimitate', premiumFeature2: '✓ Fără reclame',
    premiumFeature3: '✓ Jurnal de rugăciune', premiumFeature4: '✓ Planuri de citire biblică',
    premiumFeature5: '✓ Acces offline',
    premiumCTA: 'Începe Premium', premiumRestore: 'Restaurează cumpărătura', premiumCancel: 'Nu acum',
    navHome: 'Acasă', navChat: 'Vorbește', navBible: 'Biblie', navPrayer: 'Rugăciune', navMore: 'Mai mult',
    crisisDetected: 'Aud că treci prin ceva foarte dificil. Nu ești singur/ă. Te rog contactează pe cineva care te poate ajuta acum:',
    crisisCall: 'Sună la Linia de Criză', crisisContinue: 'Continuă conversația',
  },

  sk: {
    appName: 'Thank You Jesus',
    appTagline: 'Tvoj spoločník na ceste životom',
    selectLanguage: 'Vyber si jazyk',
    selectDenomination: 'Aká je tvoja viera?',
    continue: 'Pokračovať', back: 'Späť',
    catholic: 'Katolík', catholicDesc: 'Rímskokatolícka tradícia',
    orthodox: 'Pravoslávny', orthodoxDesc: 'Pravoslávna tradícia',
    protestant: 'Protestant / Evanjelik', protestantDesc: 'Reformovaná tradícia',
    ecumenical: 'Ekumenický', ecumenicalDesc: 'Spoločný kresťanský základ',
    seeker: 'Hľadajúci', seekerDesc: 'Zvedavý o viere',
    disclaimerTitle: 'Slovo predtým, než začneme',
    disclaimerText: 'Thank You Jesus je AI aplikácia inšpirovaná Bibliou. Nenahrádza modlitbu, Cirkev ani kňaza. V krízovej situácii sa obráť na skutočnú osobu.',
    disclaimerAgree: 'Rozumiem — začnime',
    greeting_morning: 'Dobré ráno', greeting_afternoon: 'Dobrý deň', greeting_evening: 'Dobrý večer',
    dailyVerse: 'Verš Dňa', quickTopics: 'Čo máš na srdci?', openBible: 'Otvoriť Bibliu',
    grief: 'Smútok', fear: 'Strach', decision: 'Rozhodnutie', forgiveness: 'Odpustenie',
    gratitude: 'Vďačnosť', love: 'Láska', temptation: 'Pokušenie', hope: 'Nádej',
    chatTitle: 'Rozhovor s Ježišom', chatPlaceholder: 'Zdieľaj, čo máš na srdci...', chatSend: 'Poslať',
    chatWelcome: 'Pokoj s tebou. Čo máš dnes na srdci?', chatTyping: 'Ježiš počúva...',
    freeMessages: 'bezplatných správ zostáva dnes', upgradeToPremium: 'Prejsť na Premium',
    premiumBenefits: 'Neobmedzené rozhovory · Bez reklám · Všetko zahrnuté',
    bibleTitle: 'Sväté Písmo', bibleSearch: 'Hľadaj', bibleSearchPlaceholder: 'Hľadaj tému alebo verš...',
    bibleTopics: 'Témy', noResults: 'Žiadne výsledky. Skús iné hľadanie.',
    prayerTitle: 'Modlitebná miestnosť', prayerAdd: 'Pridať úmysel', prayerPlaceholder: 'Za čo sa chceš modliť?',
    prayerAnswered: 'Označiť ako vyslyšanú', prayerEmpty: 'Tvoja modlitebná miestnosť je prázdna.',
    journalTitle: 'Duchovný denník', journalAdd: 'Nový záznam', journalPlaceholder: 'Napíš svoje myšlienky...',
    journalEmpty: 'Tvoj denník je prázdny.',
    favoritesTitle: 'Uložené verše', favoritesEmpty: 'Žiadne uložené verše.',
    settingsTitle: 'Nastavenia', settingsLanguage: 'Jazyk', settingsDenomination: 'Viera',
    settingsAbout: 'O aplikácii', settingsPrivacy: 'Ochrana súkromia', settingsVersion: 'Verzia 1.0.0',
    premiumTitle: 'Thank You Jesus Premium', premiumSubtitle: 'Neobmedzený prístup ku všetkým funkciám',
    premiumPrice: '$4.99 / mesiac', premiumYearly: '$39.99 / rok (ušetríš 33%)',
    premiumFeature1: '✓ Neobmedzené rozhovory', premiumFeature2: '✓ Bez reklám',
    premiumFeature3: '✓ Modlitebný denník', premiumFeature4: '✓ Plány čítania Biblie',
    premiumFeature5: '✓ Offline prístup',
    premiumCTA: 'Začať Premium', premiumRestore: 'Obnoviť nákup', premiumCancel: 'Teraz nie',
    navHome: 'Domov', navChat: 'Rozhovor', navBible: 'Biblia', navPrayer: 'Modlitba', navMore: 'Viac',
    crisisDetected: 'Počujem, že prechádzaš niečím veľmi ťažkým. Nie si sám/sama. Prosím, obrať sa na niekoho, kto ti môže pomôcť teraz:',
    crisisCall: 'Zavolaj na Linku pomoci', crisisContinue: 'Pokračovať v rozhovore',
  },
};

// Helper to get translation
export const t = (lang, key) => {
  const translations = T[lang] || T['en'];
  return translations[key] || T['en'][key] || key;
};

// Get daily verse (rotates by day of year)
export const getDailyVerse = () => {
  const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0)) / 86400000);
  return DAILY_VERSES_EN[dayOfYear % DAILY_VERSES_EN.length];
};

// Crisis keywords for detection
export const CRISIS_KEYWORDS = [
  'suicide', 'kill myself', 'end my life', 'want to die', 'don\'t want to live',
  'suicidio', 'matarme', 'no quiero vivir',
  'suicídio', 'me matar',
  'suicidio', 'uccidermi', 'non voglio vivere',
  'samobójstwo', 'zabić się', 'nie chcę żyć',
  'selbstmord', 'mich umbringen', 'sterben wollen',
  'suicide', 'me suicider', 'ne veux plus vivre',
  'самоубийство', 'убить себя', 'не хочу жить',
  'sinucidere', 'să mă omor',
  'samovražda', 'zabiť sa', 'nechcem žiť',
];

export const containsCrisisKeywords = (text) => {
  const lower = text.toLowerCase();
  return CRISIS_KEYWORDS.some(kw => lower.includes(kw));
};
